export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Search:'Search',
      Products:'Products',
      Add_Product:'Add Product',
      Dashboard:'Dashboard',
      Sales_Order:'Order Registration',
      Purchase_Order:'Purchase Order',
      Supplier:'Supplier',
      Customer:'Customer',
      Product_Group:'Product Group',
      Sales_Unit:'Sales Unit',
      Kilogram:'Kilogram',
      Product:'Product',
      Productcode:'Productcode',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      Producttype: 'Producttype',
      Concentration: 'Concentration',
      Addition: 'Addition',
      Description: 'Description',
      Salesunit: 'Salesunit',
      Partial: 'Partial',
      Intrastat: 'Intrastat',
      Save: 'Save',
      User: 'User',
      Add_User: 'Add User',
      FirstName: 'FirstName',
      LastName: 'LastName',
      Email: 'Email',
      Active: 'Active',
      State: 'State',
      View_User: 'View User',
      Edit_User: 'Edit User',
      UserName: 'UserName',
      Roles: 'Roles',
      ConfirmPassword: 'ConfirmPassword',
      PhoneNumber: 'PhoneNumber',
      IsActive: 'IsActive',
      Product_Details: 'Product Details',
      Productgroup: 'Productgroup',
      Purchase_Price: 'Purchase Price',
      Price: 'Price',
      Start_date: 'Start date',
      End_date: 'End date',
      Add_Purchase_Price: 'Add Purchase Price',
      Sales_Price: 'Sales Price',
      Add_Salese_Price: 'Add Salese Price',
      Transport_Price: 'Transport Price',
      Id: 'Id',
      Transporter: 'Transporter',
      Pricingtype: 'Pricingtype',
      Add_Transport_Price: 'Add Transport Price',
      Add_Sales_Order: 'Add Sales Order',
      Reference: 'Reference',
      Order_Date: 'Order Date',
      Total_amount: 'Total amount',
      Sales_Order_Details: 'Order registration details',
      Loading_Date: 'Loading Date',
      Quantity: 'Quantity',
      Amount: 'Amount',
      Add_Pursase_Order: 'Add Pursase Order',
      Invoice: 'Invoice',
      Invoice_date: 'Invoice date',
      Journal: 'Journal',
      Expiration_Date: 'Expiration Date',
      Purchase_Order_Details: 'Purchase Order Details',
      Add_row: 'Add row',
      GlCode: 'GlCode',
      VATCode: 'VATCode',
      VATAmount: 'VATAmount',
      Reporting_Date: 'Reporting Date',
      Purchase_Unit: 'Purchase Unit',
      Approver: 'Approver',
      Add_Price: 'Add Price',
      Copy_Product: 'Copy Product',
      Select: 'Select...',
      Task: 'Task',
      Task_Overview: 'Task Overview',
      Tasktype: 'Tasktype',
      Subject: 'Subject',
      TaskStatus: 'TaskStatus',
      Action: 'Action',
      Edit_Task: 'Edit Task',
      Add_Task: 'Add Task',
      Approve: 'Approve',
      Customer_Note: 'Customer Note',
      File: 'File',
      Choose_File: 'Choose File',
      Purchase_order: 'PurchaseOrder',
      Please_set_pricetype: 'Please set pricetype',
      Submit: 'Submit',
      Edit: 'Edit',
      Click_or_Drop: 'Click or Drop some files here!',
      Purchase_Order_Edit: 'Purchase Order Edit',
      Sales_Order_Edit: 'Sales Order Edit',
      Send_to_Exact: 'Send to Exact',
      Sending: 'Sending',
      Loading_date: 'Loading Date',
      Attachments: 'Attachments',
      Reference_customer: 'Reference Customer',
      Total_Purchase: 'Total Purchase',
      Total_Sales: 'Total Sales',
      DocumentType: 'DocumentType',
      IsTransport: 'IsTransport',
      PackingSlip: 'PackingSlip',
      Container: 'Container',
      Shipping: 'Shipping',
      Purchase_Amount: 'PurchaseAmount',
      Sales_Amount: 'SalesAmount',
      Packing_slip_number: 'Packing SlipNumber',
      Container_number: 'Container Number',
      ShippingDocumentnumber: 'Shipping DocumentNumber',
      Add: 'Add',
      ReportingDate: 'Reporting Date',
      Number: 'Number',
      Quality: 'Quality',
      Complete: 'Complete',
      No_Result: 'No Result',
      Total: 'Total',
      Purchase: 'Purchase',
      Transport: 'Transport'
    },


    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Search:'Zoeken',
      Products:'Artikelen',
      Add_Product:'Toevoegen product',
      Dashboard:'Dashboard',
      Sales_Order:'Order Registratie',
      Purchase_Order:'Inkooporder',
      Purchase_Order_Edit:'Bewerk inkooporder',
      Supplier:'Leverancier',
      Customer:'Klant',
      Product_Group:'Artikelgroep',
      Sales_Unit:'Verkoopeenheid',
      Kilogram:'Kilogram',
      Product:'Artikel',
      Productcode:'Artikelcode',
      Previous:'Vorige',
      Next:'Volgende',
      Show_entries:'Toon records',
      Show:'Toon',
      Entries:'Records',
      Show_page:'Pagina weergeven',
      Producttype: 'Artikelsoort',
      Concentration: 'Concentratie',
      Addition: 'Toevoeging',
      Description: 'Omschrijving',
      Salesunit: 'Verkoopeenheid',
      Partial: 'Delen',
      Intrastat: 'Intrastat',
      Save: 'Opslaan',
      User: 'Gebruiker',
      Add_User: 'Voeg gebruiker toe',
      FirstName: 'Voornaam',
      LastName: 'Achternaam',
      Email: 'E-mail',
      Active: 'Actief',
      State: 'Status',
      View_User: 'Bekijk gebruiker',
      Edit_User: 'Bewerk gebruiker',
      UserName: 'Gebruikersnaam',
      Roles: 'Rollen',
      ConfirmPassword: 'Bevestig wachtwoord',
      PhoneNumber: 'Telefoonnummer',
      IsActive: 'Is actief',
      Product_Details: 'Product details',
      Productgroup: 'Productgroep',
      Purchase_Price: 'Inkoopprijs',
      Price: 'Prijs',
      Start_date: 'Begindatum',
      End_date: 'Einddatum',
      Add_Purchase_Price: 'Inkoopprijs toevoegen',
      Sales_Price: 'Verkoopprijs',
      Add_Salese_Price: 'Verkoopprijs toevoegen',
      Transport_Price: 'Transportprijs',
      Id: 'Id',
      Transporter: 'Vervoerder',
      Pricingtype: 'Prijstype',
      Add_Transport_Price: 'Voeg transportprijs toe',
      Add_Sales_Order: 'Verkooporder toevoegen',
      Reference: 'Referentie',
      Order_Date: 'Besteldatum',
      Total_amount: 'Totaalbedrag',
      Sales_Order_Details: 'Order registratie details',
      Loading_Date: 'Laaddatum',
      Quantity: 'Aantal',
      Amount: 'Bedrag',
      Add_Pursase_Order: 'Toevoegen inkooporder',
      Invoice: 'Factuur',
      Invoice_date: 'Factuurdatum',
      Journal: 'Dagboek',
      Expiration_Date: 'Vervaldatum',
      Purchase_Order_Details: 'Inkooporder details',
      Add_row: 'Rij toevoegen',
      GlCode: 'Grootboekrekening',
      VATCode: 'BTW code',
      VATAmount: 'BTW bedrag',
      Reporting_Date: 'Rapportagedatum',
      Purchase_Unit: 'Inkoopeenheid',
      Approver: 'Goedkeurder',
      Add_Price: 'Prijs toevoegen',
      Copy_Product: 'Artikel kopiëren',
      Select: 'Selecteer...',
      Task: 'Taak',
      Task_Overview: 'Taak overzicht',
      Tasktype: 'Taaktype',
      Subject: 'Onderwerp',
      TaskStatus: 'Taak status',
      Action: 'Actie',
      Edit_Task: 'Bewerk taak',
      Add_Task: 'Toevoegen taak',
      Approve: 'Goedkeuren',
      Customer_Note: 'Klant notitie',
      File: 'Bestand',
      Choose_File: 'Kiezen bestand',
      Purchase_order: 'Inkooporder',
      Please_set_pricetype: 'Instellen prijstype',
      Submit: 'Indienen',
      Edit: 'Bewerk',
      Click_or_Drop: 'Klik of sleep uw bestanden!',
      Sales_Order_Edit: 'Verkooporder bewerken',
      Send_to_Exact: 'Verstuur naar Exact',
      Sending: 'Verzending',
      Loading_date: 'Laaddatum',
      Attachments: 'Bijlagen',
      Reference_customer: 'Referentie klant',
      Total_Purchase: 'Totaal inkoop',
      Total_Sales: 'Totaal verkoop',
      DocumentType: 'DocumentType',
      IsTransport: 'Is transport',
      PackingSlip: 'Pakbon nummer',
      Container: 'Container nummer',
      Shipping: 'Vrachtbrief nummer',
      Purchase_Amount: 'Inkoop bedrag',
      Sales_Amount: 'Verkoop bedrag',
      Packing_slip_number: 'Pakbon nummer',
      Container_number: 'Container nummer',
      ShippingDocumentnumber: 'Container nummer',
      Add: 'Toevoegen',
      ReportingDate: 'Rapportage Datum',
      Number: 'Aantal',
      Quality: 'Controle',
      Complete: 'Compleet',
      No_Result: 'Geen resultaat',
      Total: 'Totaal',
      Purchase: 'Inkoop',
      Transport: 'Transport'
    }
  };