export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Orders: 'Orders',
      Dashboard: 'Dashboard',
      Sales_No: 'Sales No',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      PO_No: 'PO_No',
      Order_Date: 'OrderDate',
      Shipping_Date: "ShippingDate",
      Total: 'Total',
      Currency: 'Currency',
      Status: 'Status',
      Download: 'Download',
      Past_Due: 'Past Due',
      Due_Soon: 'Due Soon',
      Total_Outstanding: 'Total Outstanding',
      Place_an_order: 'Place an order',
      Search_Lines: 'Search Products and Create Order Lines',
      Make_a_Payment: 'Make a Payment',
      Credit_card: 'Credit card, PayPal, Worldpay, On Account',
      Last_5_Orders: 'Last 5 Orders',
      Next_5_Deliveries_Due: 'Next 5 Deliveries Due',
      Outstanding_Payments: 'Outstanding Payments',
      Sales_Number: 'Sales Number',
      Delivery_Number: 'Delivery Number',
      Due_Date: 'Due Date',
      Invoice_Number: 'Invoice Number',
      Amount: 'Amount',
      Enter_email: 'EnterEmail',
      Back_to_Sign_in: 'Back to Sign in',
      Next_Step: 'Next Step',
      New_Password: 'NewPassword',
      Confirm_Password: 'ConfirmPassword',
      Item_Name: 'ItemName',
      Description: 'Description',
      Quantity: 'Quantity',
      Shipped_Quantity: 'ShippedQuantity',
      Price: 'Price',
      Requested_Delivery_Date: 'Requested Delivery Date',
      PO_Reference: 'PO Reference',
      Billing_Address: 'Billing Address',
      Shipping_Address: 'Shipping Address',
      Order_Comments: 'Order Comments',
      Product_Lookup: 'Product Lookup',
      Item_Price: 'ItemPrice',
      Line_Total: 'Line Total',
      Click_to_make_new_row: 'Click to make new row',
      Search: 'Search',
      Submit_Order: 'Submit Order',
      Make_a_payment: 'Make a payment',
      Make_Payment: 'Make Payment',
      Play: 'Play',
      Type: 'Type',
      Documet_Date: 'DocumentDate',
      Invoice_No: 'Invoice No'
    },


    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Orders: 'Vestellen',
      Dashboard: 'Dashboard',
      Sales_No: 'Verkoop No',
      Previous:'Vorige',
      Next:'Volgende',
      Show_entries:'Toon records',
      Show:'Toon',
      Entries:'Records',
      Show_page:'Pagina weergeven',
      PO_No: 'PO_No',
      Order_Date: 'BestellenDatum',
      Shipping_Date: 'VerzendingDatum',
      Total: 'Totaal',
      Currency: 'Valuta',
      Status: 'Toestand',
      Download: 'Download',
      Past_Due: 'Verleden Due',
      Due_Soon: 'Due Spoedig',
      Total_Outstanding: 'Totaal Voortreffelijk',
      Place_an_order: 'Een bestelling plaatsen',
      Search_Lines: 'Zoek producten en maak orderregels',
      Make_a_Payment: 'Maak een betaling',
      Credit_card: 'Creditcard, PayPal, Worldpay, op account',
      Last_5_Orders: 'Laatste 5 bestellingen',
      Next_5_Deliveries_Due: 'Volgende 5 Leveringen verschuldigd',
      Outstanding_Payments: 'Openstaande betalingen',
      Sales_Number: 'Verkoop Aantal',
      Delivery_Number: 'Levering Aantal',
      Due_Date: 'Due Datum',
      Invoice_Number: 'Factuur Aantal',
      Amount: 'Bedrag',
      Enter_email: 'InvoerenEmail',
      Back_to_Sign_in: 'Terug naar inloggen',
      Next_Step: 'Volgende Stap',
      New_Password: 'Nieuw Wachtwoord',
      Confirm_Password: 'Bevestigen Wachtwoord',
      Item_Name: 'ItemNaam',
      Description: 'Beschrijving',
      Quantity: 'Aantal',
      Shipped_Quantity: 'Verunden Aantal',
      Price: 'Prijs',
      Requested_Delivery_Date: 'Gevraagde afleverdatum',
      PO_Reference: 'Po Referenie',
      Billing_Address: 'Factuur Adres',
      Shipping_Address: 'Verzending  Adres',
      Order_Comments: 'Bestellen Comments',
      Product_Lookup: 'Product Opzoeken',
      Item_Price: 'ItemPrijs',
      Line_Total: 'Lijn Totaal',
      Click_to_make_new_row: 'Click om een ​​nieuwe rij te maken',
      Search: 'Zoeken',
      Submit_Order: 'Voorleggen Bestellen',
      Make_a_payment: 'Maken een betaling',
      Make_Payment: 'Maken Betaling',
      Play: 'Speel',
      Type: 'Type',
      Documet_Date: 'DocumentDatum',
      Invoice_No: 'Factuur No'
    }
  };