const BASEURL = 'https://app-test.organisatie.freepeat.com';
export default {
    GetToken: "https://app-test.organisatie.freepeat.com/token",
    GetUserData: `${BASEURL}/api/users/GetUsers?excludeActiveUsers=false`,
    PostUserData: `${BASEURL}/api/Users`,
    DeleteUserData: `${BASEURL}/api/Users/`,
    GetUserDataById: `${BASEURL}/api/Users/`,
    PostUserUpdate: `${BASEURL}/api/Users`,
    PostProductData: `${BASEURL}/api/factory/execute/Appmakerz-Test/postProduct`,
    PostCopyProduct: `${BASEURL}/api/factory/execute/Appmakerz-Test/copyProduct`,
    GetProductData: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProducts`,
    GetSupplierList: `${BASEURL}/api/factory/execute/Exact-Test/getSuppliersDropdown`,
    GetProductType: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProductTypesDropdown`,
    GetSalesUnit: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesUnitsDropdown`,
    GetProductGroup: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProductGroupsDropdown`,
    GetUnitData: `${BASEURL}/api/factory/execute/Exact-Test/getUnitsDropdown`,
    GetSalesData: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrders`,
    GetCustomerData: `${BASEURL}/api/factory/execute/Exact-Test/getCustomersDropdown`,
    PostSalesOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrder`,
    GetSalesDetail: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrder`,
    GetSalesItems: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesItemsDropdown`,
    GetSalesItemsPrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesPrice`,
    PostSalesOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrderLine`,
    GetSalesOrderLines: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrderLines`,
    GetSuppliersDropdown: `${BASEURL}/api/factory/execute/Exact-Test/getSuppliersDropdown`,
    GetJournalsDropdown: `${BASEURL}/api/factory/execute/Exact-Test/getJournalsDropdown`,
    PostPurchaseOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrder`,
    GetPurchaseOrders: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrders`,
    GetPurchaseOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrder`,
    GetPurchaseItems: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseItemsDropdown`,
    GetGlCode: `${BASEURL}/api/factory/execute/Exact-Test/getGlCodeDropdown`,
    GetVATCode: `${BASEURL}/api/factory/execute/Exact-Test/getVATCodeDropdown`,
    GetPurchasePrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchasePrice`,
    PostPurchaseOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrderLine`,
    GetPurchaseOrderLines: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrderLines`,
    GetTransportPrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportPrices`,
    PostPricechangeTask: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPricechangeTask`,
    GetTasks: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTasks`,
    GetTaskById: `${BASEURL}/api/factory/execute/appmakerz-test/getTaskById`,
    GetTasktypeDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getTasktypeDropdown`,
    GetTaskstatusDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getTaskstatusDropdown`,
    GetProductsDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getProductsDropdown`,
    GetUsersDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getUsersDropdown`,
    PutTask: `${BASEURL}/api/factory/execute/appmakerz-test/putTask`,
    ApprovePurchasePrice: `${BASEURL}/api/factory/execute/appmakerz-Test/ApprovePurchasePrice`,
    GetProduct: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProduct`,
    GetPurchasePrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchasePrices`,
    GetSalesPrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesPrices`,
    GetTransportPrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportPrices`,
    ApproveSalesPrice : `${BASEURL}/api/factory/execute/Appmakerz-Test/ApproveSalesPrice`,
    ApproveTransportPrice : `${BASEURL}/api/factory/execute/Appmakerz-Test/ApproveTransportPrice`,
    FileUpload : `${BASEURL}/api/factory/upload-file`,
    GetPurchaseOrderDropdown : `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrderDropdown`,
    PostTransportPrice : `${BASEURL}/api/factory/execute/Appmakerz-Test/postTransportPrice`,
    GenerateProductXmlExact : `${BASEURL}/api/exact/GenerateProductXmlExact`,
    PostPurchaseDocument : `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseDocument`,
    GeneratePurchaseInvoiceXmlExact : `${BASEURL}/api/exact/GeneratePurchaseInvoiceXmlExact`,
    GenerateSalesInvoiceXmlExact : `${BASEURL}/api/exact/GenerateSalesInvoiceXmlExact`,
    PutPurchaseOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/putPurchaseOrder`,
    PutSalesOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/putSalesOrder`,
    PostProductsExact: `${BASEURL}/api/factory/execute/Appmakerz-Test/postProductsExact`,
    PostProductsExactSend: `${BASEURL}/api/factory/execute/Appmakerz-Test/postProductsExactSend`,
    PostPurchaseOrderExact: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrderExact`,
    PostPurchaseOrderExactSend: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrderExactSend`,
    PostSalesOrderExact: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrderExact`,
    PostSalesOrderExactSend: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrderExactSend`,
    GetDocumenttypesDropdown: `${BASEURL}/api/factory/execute/Appmakerz-Test/getDocumenttypesDropdown`,
    PostOrderDocument: `${BASEURL}/api/factory/execute/Appmakerz-Test/postOrderDocument`,
    GetSalesPrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesPrice`,
    PostTransports: `${BASEURL}/api/factory/execute/Appmakerz-Test/postTransports`,
    PutSalesOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/putSalesOrderLine`,
    GetSalesOrderTransports: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrderTransports`,
    GetOrderLinesByPacking: `${BASEURL}/api/factory/execute/Appmakerz-Test/getOrderLinesByPacking`,
    GetOrderLinesByContainer: `${BASEURL}/api/factory/execute/Appmakerz-Test/getOrderLinesByContainer`,
    GetOrderLinesByShipping: `${BASEURL}/api/factory/execute/Appmakerz-Test/getOrderLinesBySHipping`,
    PostPurchaseLines : `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseLines`,
    PutSalesPurchaseId : `${BASEURL}/api/factory/execute/Appmakerz-Test/putSalesPurchaseId`,
    GetQualityControl : `${BASEURL}/api/factory/execute/Appmakerz-Test/getQualityControl`,
    CompleteOrder : `${BASEURL}/api/factory/execute/Appmakerz-Test/completeOrder`,
    GetTransportersDropdown : `${BASEURL}/api/factory/execute/exact-test/getTransportersDropdown`,
    GetTransportLinesByShipping: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportLinesByShipping`,
    GetTransportLinesByContainer: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportLinesByContainer`,
    GetTransportLinesByPacking: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportLinesByPacking`,
    DeleteSalesOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/deleteSalesOrderLine`,
    PutTransports: `${BASEURL}/api/factory/execute/Appmakerz-Test/putTransports`,
    DeleteTransports: `${BASEURL}/api/factory/execute/Appmakerz-Test/deleteTransports`,
    PostPurchaseLinesTransport: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseLinesTransport`,
    PutTransportPurchaseId: `${BASEURL}/api/factory/execute/Appmakerz-Test/putTransportPurchaseId`,
  };
  
  